# Enable the newline at the start of the prompt
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Format Powerline prompt
format = """
($username)($hostname)( $memory_usage)( $battery)( $aws)( $azure)
[ ](bg:#1C4961)[$directory](bg:#1C4961)[\uE0B0](fg:#1C4961 bg:#2F79A1)$git_branch[\uE0B0](fg:#2F79A1 bg:#3A95C7)[$git_status](green bg:#3A95C7)[\uE0B0](#3A95C7 bg:#40A9E0)$time[\uE0B0](#40A9E0 bg:none) 
$shell$character """

[aws]
symbol = "[ï‰°](fg:#F0861E)"
format = 'on [$symbol ($profile )(\($region\) )(\[$duration\])]($style)'
style = "fg:#A65117"
disabled = false

[azure]
format = "on [$symbol( $subscription)]($style)"
symbol = "[ï´ƒ](fg:#0078D4)"
style = "fg:#174276"
disabled = false

[[battery.display]]
threshold = -1
style = "bold blue"
charging_symbol = "[âš¡](fg:yellow)"
discharging_symbol = "ğŸ’¦"

[battery]
full_symbol = "[ï•¸ ](fg:green)"
charging_symbol = "[ï–ƒ ](fg:green)"
discharging_symbol = "[ï–‚ğŸ’¦](fg:yellow)"
unknown_symbol = "[ï•¼ ](fg:gray)"
empty_symbol = "[ï– ](fg:red)"
style = "fg:#666666"
format = "[$symbol:$persentage]($style)"
disabled = false

[character]
format = "$symbol"
success_symbol = "[â¡](bold green)"
error_symbol = "âŒ"

[directory]
style = "bg:#1C4961 fg:white"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:#2F79A1 fg:white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "ğŸ’ PICKING"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#3A95C7"
conflicted = "ğŸ’¥"
ahead = "ğŸğŸ’¨"
behind = "ğŸ”™"
diverged = "ğŸ˜µ"
untracked = "â”"
stashed = "ğŸ“¦"
modified = "â—"
staged = '[(++\($count\))](fg:#005F00 bg:#3A95C7 bold)'
up_to_date = "[âœ”](fg:#007F00 bg:#3A95C7)"
renamed = "ğŸ–"
deleted = "ğŸ—‘"

[hostname]
ssh_only = false
trim_at = ""
style = "bold fg:#333333"
format = "[(@$hostname)]($style)"
disabled = false

[memory_usage]
format = "ï¡š [${ram}( | ${swap})]($style)"
threshold = -1
symbol = " "
style = "fg:#333333"
disabled = false

[package]
style = "#ffc0cb"
symbol = "ğŸ“¦"

[shell]
bash_indicator = "bash "
fish_indicator = "fish "
zsh_indicator = "zsh  "
powershell_indicator = "pwsh "
ion_indicator = "ion  "
elvish_indicator = "elvsh "
tcsh_indicator = "tcsh "
xonsh_indicator = "xonsh "
cmd_indicator = "cmd "
nu_indicator = "nush "
unknown_indicator = "??? "
format = "[$indicator]($style)"
style = "fg:#333333 bold"
disabled = false

[time]
disabled = false
format = "[ $time ]($style)"
style = "bg:#40A9E0 fg:white"

[username]
style_root = "bold red"
style_user = "bold fg:#666666"
show_always = true
format = "[ïŠ½ ](fg:#333333 bold) [$user]($style)"
disabled = false
