# Enable the newline at the start of the prompt
add_newline = true

# Wait 100 milliseconds for starship to check files under the current directory.
scan_timeout = 100

# Wait 1 second for starship to execute a command
command_timeout = 1000

# Format Powerline prompt
format = """
($username)($hostname)( $memory_usage)( $battery)( $aws)( $azure)
[ ](bg:#174276)[$directory](bg:#174276)[\uE0B0](fg:#174276 bg:#235A9F)$git_branch[\uE0B0](fg:#235A9F bg:#0078D4)[$git_status](green bg:#0078D4)[\uE0B0](fg:#0078D4 bg:#559CE4)$time[\uE0B0](fg:#559CE4 bg:none) 
$shell$character """

[aws]
symbol = "[ï‰°](fg:#F0861E)"
format = '[on](fg:#ADD8FF) [$symbol ($profile )(\($region\) )(\[$duration\])]($style)'
style = "fg:#A65117"
disabled = false

[azure]
format = "[on](fg:#ADD8FF) [$symbol( $subscription)]($style)"
symbol = "[ï´ƒ](fg:#0078D4)"
style = "fg:#174276"
disabled = false

[[battery.display]]
threshold = -1
style = "bold blue"
charging_symbol = "[âš¡](fg:yellow)"
discharging_symbol = "ğŸ’¦"

[battery]
full_symbol = "[ï•¸ ](fg:green)"
charging_symbol = "[ï–ƒ ](fg:green)"
discharging_symbol = "[ï–‚ğŸ’¦](fg:yellow)"
unknown_symbol = "[ï•¼ ](fg:gray)"
empty_symbol = "[ï– ](fg:red)"
style = "fg:#235A9F"
format = "[$symbol:$persentage]($style)"
disabled = false

[character]
format = "$symbol"
success_symbol = "[â¡](bold green)"
error_symbol = "âŒ"

[directory]
read_only = " ğŸ”’"
read_only_style = "fg:#174276 bg:#174276"
style = "bg:#174276 fg:white"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:#235A9F fg:white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "ğŸ’ PICKING"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#0078D4"
conflicted = "ğŸ’¥"
ahead = "ğŸğŸ’¨"
behind = "ğŸ”™"
diverged = "ğŸ˜µ"
untracked = "â”"
stashed = "ğŸ“¦"
modified = "â—"
staged = '[(++\($count\))](fg:#005F00 bg:#0078D4 bold)'
up_to_date = "[âœ”](fg:#007F00 bg:#0078D4)"
renamed = "ğŸ–"
deleted = "ğŸ—‘"

[hostname]
ssh_only = false
trim_at = ""
style = "bold fg:#0078D4"
format = "[(@$hostname)]($style)"
disabled = false

[memory_usage]
format = "[ï¡š](fg:#ADD8FF) [$ram](fg:#599CE4)( [|](fg:#ADD8FF) [$swap](fg:#0078D4))($style)"
threshold = -1
symbol = " "
style = "fg:#ADD8FF"
disabled = false

[package]
style = "#ffc0cb"
symbol = "ğŸ“¦"

[shell]
bash_indicator = "bash "
fish_indicator = "fish "
zsh_indicator = "zsh  "
powershell_indicator = "pwsh "
ion_indicator = "ion  "
elvish_indicator = "elvsh "
tcsh_indicator = "tcsh "
xonsh_indicator = "xonsh "
cmd_indicator = "cmd "
nu_indicator = "nush "
unknown_indicator = "??? "
format = "[$indicator]($style)"
style = "fg:#0078D4 bold"
disabled = false

[time]
disabled = false
format = "[ ïº $time ]($style)"
style = "bg:#559CE4 fg:white"

[username]
style_root = "bold fg:#DC322F"
style_user = "bold fg:#559CE4"
show_always = true
format = "[ï€‡](fg:#ADD8FF bold) [$user]($style)"
disabled = false
