# Enable the newline at the start of the prompt
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Format Powerline prompt
format = """
[ ](bg:#1C4961)[$directory](bg:#1C4961)[\uE0B0](fg:#1C4961 bg:#2F79A1)$git_branch[\uE0B0](fg:#2F79A1 bg:#3A95C7)[$git_status](green bg:#3A95C7)[\uE0B0](#3A95C7 bg:#40A9E0)$time[\uE0B0](#40A9E0 bg:none) $all$character """

[[battery.display]]
threshold = 100
style = "bold blue"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸª¦"

[character]
format = "$symbol"
success_symbol = "[â¡](bold green)"
error_symbol = "âŒ"

[directory]
style = "bg:#1C4961 fg:white"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:#2F79A1 fg:white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "ğŸ’ PICKING"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#3A95C7"
conflicted = "ğŸ’¥"
ahead = "ğŸğŸ’¨"
behind = "ğŸ”™"
diverged = "ğŸ˜µ"
untracked = "â”"
stashed = "ğŸ“¦"
modified = "â—"
staged = '[(++\($count\))](fg:#005F00 bg:#3A95C7 bold)'
up_to_date = "[âœ”](fg:#007F00 bg:#3A95C7)"
renamed = "ğŸ–"
deleted = "ğŸ—‘"

[hostname]
ssh_only = false
trim_at = ""
disabled = true

[memory_usage]
format = "[${ram_pct}(${swap_pct})]($style) "
threshold = -1
symbol = " "
style = "bold dimmed green"

[package]
style = "#ffc0cb"
symbol = "ğŸ“¦"

[time]
disabled = false
format = "[ $time ]($style)"
style = "bg:#40A9E0 fg:white"

[username]
style_root = "bold red"
style_user = "bold white"
show_always = true
disabled = false
